server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmt?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: lixinkai
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 47.119.135.236
    port: 6379
    password: lixinkai
    timeout: 10000
    jedis:
      pool:
        max-wait: 100
        max-active: 32
        max-idle: 8
        min-idle: 4
    database: 0
  cache:
    redis:
      time-to-live: 10m
    cache-names: user, role, node

  mqtt:
    username: admin
    password: lixinkai
    url: tcp://47.119.135.236:1883
    clientId: mqttClient
    topic: warehouse/#
    completionTimeout: 2000

  mail:
    ## 编码
    default-encoding: utf-8
    ## 邮件服务器
    host: smtp.163.com
    ## 服务协议
    protocol: smtp
    ## 发送邮件的用户名
    username: lixinkai1997@163.com
    ## 授权码
    password: DZKVHRBZQVGJVEAN
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true




mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
logging:
  level:
    com.mybestcoding.hmt.mapper: debug


redistimeseries:
  host: 47.119.135.236
  port: 6379
  password: lixinkai